project:
  type: website
  output-dir: docs
  
website:
  title: "Skin and Bone in London, 1760-1901"
  site-url: https://skin-and-bone-in-london-1760-1901.github.io/
  description: "A data blog for the Skin and Bone project"
  favicon: favicon.jpg
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd 
      - icon: rss
        href: blog.xml
        
format:
  html:
    theme: united
    css: styles.css
    toc: true
    #code-fold: true



date-format: "D MMMM YYYY"



