---
title: "Skin and Bone"
subtitle: "Interdisciplinary analysis of accidents, injury, and violence in industrialising London, 1760-1901"
listing:
  - id: posts-table
    contents: posts
    sort: "date desc"
    max-items: 4
    type: table
    fields: [date, title]
    categories: false
    sort-ui: false
    filter-ui: false
    date-format: "D MMM YYYY"
    feed: true
format:
  html:
    toc: false
page-layout: article
---


Skin and Bone seeks to chart the embodied experience of work-related injury, accidents, and interpersonal violence of c.170,000 Londoners during the Industrial Revolution. Led by a historian of the period, with expertise in digital humanities, and an osteoarchaeologist who has collated data on trauma and injury in eighteenth-century bodies, the project will generate a new open-access multivariate database and develop innovative approaches to studying and visualising the historic material body - skin and bone - in London during the Industrial Revolution.


In both archaeology and history, the period 1760-1901 represents a significant transformation for the body. Injuries, accidents and interpersonal violence profoundly affected lived experiences of the body in England during the intense period of industrialisation between 1760 and 1901. 
Osteoarchaeological scholarship has increasingly examined the negative impacts of the process of industrialisation. Historians, too, have discussed the impact of industrialisation on the body, specifically how new urban contexts damaged life expectancy while also changing attitudes to bodies that defined new social identities and social relationships, notably a new class of poor labouring bodies and hardening concepts of the able and disabled body. 

Osteoarchaeology datasets in combination with hospital and criminal justice records, which note age, gender and occupation alongside many bodily features (such as deformities and scars), provide a means of accessing and contextualising embodied experiences of industrialising London, but this information is currently held within disparate datasets. 
The project will merge ten datasets compiled from criminal, hospital, and osteoarchaeological records to explore the relationships between trauma, injury, and accidents with social demographics, but especially, sex/gender, age and occupational status. 

The first technical challenge is to extract and classify detailed evidence on over 170,000 individuals, including their physical characteristics, bodily infirmities and personal details. The language used to describe injuries in the data is highly varied across the datasets, and it can be difficult to classify and standardise the nature of injury. In addition to the challenge of merging, extracting and classifying the data, a second technical challenge exists in coping with the complexity of the multiple variables available and in summarising such diverse data. In order to deal with this complexity, and examine the links between the datasets, new visualisations need to be developed to summarise this multivariate data.


## Further reading

David Turner and Daniel Blackie, [Disability in the Industrial Revolution](https://library.oapen.org/handle/20.500.12657/30580) (oa book)

[Disability and Industrial Society](https://www.dis-ind-soc.org.uk/en/index.htm)

Cooter, R., and B. Luckin (eds), *Accidents in History: Injuries, Fatalities and Social Relations* (Amsterdam, 1997)

Risse, G. B., *Hospital Life in Enlightenment Scotland: Care and Teaching at the Royal Infirmary of Edinburgh* (Cambridge/New York, 1986)



## Recent Posts

::: {#posts-table}
:::

[All posts](blog.qmd)


## Credits

The project is funded by the [British Academy](https://www.thebritishacademy.ac.uk/) (2022-23).

The project directors are [Zoe Alker, University of Lancaster](https://www.lancaster.ac.uk/arts-and-social-sciences/people/zoe-alker), and [Madeleine Mant, University of Toronto](https://www.anthropology.utoronto.ca/people/directories/all-faculty/madeleine-mant).

Project technical development is carried out by the [Digital Humanities Institute | Sheffield](https://www.dhi.ac.uk/).

This blog has been built by [Sharon Howard](http://sharonhoward.org), with help from [RStudio](https://www.rstudio.com/), [Quarto](https://quarto.org/) and [Github](https://github.com/).
